# Generated by Django 3.1.1 on 2020-09-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dostępnośćPoczątek', models.DateField()),
                ('dostępnośćZakończenie', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='DziałPrzedmiotu',
            new_name='DzialPrzedmiotu',
        ),
        migrations.RenameField(
            model_name='opinia',
            old_name='opinia',
            new_name='opis',
        ),
        migrations.RenameField(
            model_name='przedmiot',
            old_name='użytkownikUdostępniający',
            new_name='uzytkownikUdostępniający',
        ),
        migrations.RemoveField(
            model_name='opinia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='przedmiot',
            name='działPrzedmiotu',
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='dzialPrzedmiotu',
            field=models.ManyToManyField(to='wypozyczalnia.DzialPrzedmiotu'),
        ),
        migrations.RenameModel(
            old_name='Użytkownik',
            new_name='Uzytkownik',
        ),
        migrations.DeleteModel(
            name='Wypożyczenie',
        ),
        migrations.AddField(
            model_name='wypozyczenie',
            name='przedmiot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.przedmiot'),
        ),
        migrations.AddField(
            model_name='wypozyczenie',
            name='uzytkownik',
            field=models.ManyToManyField(to='wypozyczalnia.Uzytkownik'),
        ),
        migrations.AddField(
            model_name='opinia',
            name='wypozyczenia',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wypozyczalnia.wypozyczenie'),
            preserve_default=False,
        ),
    ]
