# Generated by Django 3.1.1 on 2020-09-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_auto_20200913_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='avatar',
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='numertelefonu',
            field=models.CharField(default='null', max_length=12),
            preserve_default=False,
        ),
    ]
