# Generated by Django 3.1.1 on 2020-09-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0003_auto_20200916_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='wypozyczenie',
            name='informacjeDodatkowe',
            field=models.TextField(null=True),
        ),
    ]
