# Generated by Django 3.1.1 on 2020-10-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0005_auto_20201002_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przedmiot',
            name='dzialPrzedmiotu',
            field=models.ManyToManyField(blank=True, null=True, to='wypozyczalnia.DzialPrzedmiotu'),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
