# Generated by Django 3.1.1 on 2020-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0006_auto_20201002_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przedmiot',
            name='dostępnośćPoczątek',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='dostępnośćZakończenie',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
