# Generated by Django 3.1.1 on 2020-10-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0007_auto_20201002_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='hasło',
            new_name='haslo',
        ),
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='imię',
            new_name='imie',
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='zdjęcie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
