# Generated by Django 3.1.1 on 2020-10-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0010_auto_20201005_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinia',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opinia',
            name='skalaZadowolenia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
