# Generated by Django 3.1.1 on 2020-10-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0011_auto_20201005_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinia',
            name='uzytkownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.uzytkownik'),
        ),
    ]
