# Generated by Django 3.1.1 on 2020-10-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0012_auto_20201005_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinia',
            name='wypozyczenia',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wypozyczalnia.wypozyczenie'),
        ),
    ]
