# Generated by Django 3.1.1 on 2020-10-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0013_auto_20201005_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinia',
            name='wypozyczenia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wypozyczalnia.wypozyczenie'),
        ),
    ]
