# Generated by Django 3.1.1 on 2020-10-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0014_auto_20201005_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przedmiot',
            name='miasto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='nazwa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='opisPrzedmiotu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
