# Generated by Django 3.1.1 on 2020-10-09 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wypozyczalnia', '0015_auto_20201005_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='miasto',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='nazwa',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='opisPrzedmiotu',
            field=models.TextField(null=True),
        ),
    ]
