# Generated by Django 3.1.1 on 2020-10-22 10:52

from django.db import migrations, models
import wypozyczalnia.models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0017_auto_20201009_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przedmiot',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='zdjęcie',
            field=models.ImageField(default='posts/default.jpg', upload_to=wypozyczalnia.models.upload_to, verbose_name='Image'),
        ),
    ]
