# Generated by Django 3.1.1 on 2020-10-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0019_auto_20201022_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przedmiot',
            name='zdjecie',
            field=models.ImageField(upload_to='przedmiot', verbose_name='Image'),
        ),
    ]
