# Generated by Django 3.1.1 on 2020-10-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0020_auto_20201027_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='przedmiot',
            old_name='dostępnośćPoczątek',
            new_name='dostepnoscPoczetek',
        ),
        migrations.RenameField(
            model_name='przedmiot',
            old_name='dostępnośćZakończenie',
            new_name='dostepnoscZakonczenie',
        ),
    ]
