# Generated by Django 3.1.1 on 2020-10-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0021_auto_20201027_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='przedmiot',
            old_name='dostepnoscPoczetek',
            new_name='dostepnoscPoczatek',
        ),
        migrations.RenameField(
            model_name='wypozyczenie',
            old_name='dostępnośćPoczątek',
            new_name='dostepnoscPoczatek',
        ),
        migrations.RenameField(
            model_name='wypozyczenie',
            old_name='dostępnośćZakończenie',
            new_name='dostepnoscZakonczenie',
        ),
    ]
