# Generated by Django 3.1.1 on 2020-11-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0022_auto_20201027_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wypozyczenie',
            old_name='dostepnoscPoczatek',
            new_name='wypozyczeniePoczatek',
        ),
        migrations.RenameField(
            model_name='wypozyczenie',
            old_name='dostepnoscZakonczenie',
            new_name='wypozyczenieZakonczenie',
        ),
    ]
