# Generated by Django 3.1.1 on 2020-11-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0023_auto_20201104_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='przedmiot',
            old_name='uzytkownikUdostępniający',
            new_name='uzytkownikUdostepniajacy',
        ),
    ]
