# Generated by Django 3.1.1 on 2020-11-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0024_auto_20201104_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wypozyczenie',
            name='uzytkownik',
        ),
        migrations.AddField(
            model_name='wypozyczenie',
            name='uzytkownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.uzytkownik'),
        ),
    ]
