# Generated by Django 3.1.1 on 2021-01-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0025_auto_20201106_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='przedmiot',
            name='cena',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='przedmiot',
            name='dzialPrzedmiotu',
            field=models.ManyToManyField(blank=True, null=True, related_name='dzial', to='wypozyczalnia.DzialPrzedmiotu'),
        ),
    ]
