# Generated by Django 3.1.1 on 2021-01-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0028_auto_20210118_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinia',
            name='przedmiot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.przedmiot'),
        ),
    ]
