# Generated by Django 3.1.1 on 2021-01-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0030_auto_20210118_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinia',
            name='przedmiot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.przedmiot'),
        ),
    ]
