# Generated by Django 3.1.1 on 2021-01-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0035_auto_20210122_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przedmiot',
            name='dzialPrzedmiotu',
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='dzialPrzedmiotu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dzial', to='wypozyczalnia.dzialprzedmiotu'),
        ),
    ]
