# Generated by Django 3.1.1 on 2021-01-24 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0036_auto_20210124_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przedmiot',
            name='dzialPrzedmiotu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dzial', to='wypozyczalnia.dzialprzedmiotu'),
        ),
    ]
